# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b67e754b5dd720a440c7eb6408c297a6abd23e82ab9ee16a26b1210ab17a2be4f57d775a12ebf094c578abb9969604e70cbd2c59742824a2142ba035b440c33

test:
  secret_key_base: d08586cfe8dd60b564f648c1b6acc2b6c191e5278ba05a7bb73c8b279cd272b045123f5989e50bacfb288134605726f1e484322baf23dd6108212ed7ec51ebf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
